// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9hW2mUy9y160q-_WXKwbzRm-1yJEIRs',
    appId: '1:514086238242:web:e5f21b085727bbdcc5327b',
    messagingSenderId: '514086238242',
    projectId: 'sunify-4286b',
    authDomain: 'sunify-4286b.firebaseapp.com',
    storageBucket: 'sunify-4286b.firebasestorage.app',
    measurementId: 'G-X9LTVFLKXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12zNLP0hReNsJlx1kFgnjzQ2c-pQqlqY',
    appId: '1:514086238242:android:dd1f8c80b2d4e766c5327b',
    messagingSenderId: '514086238242',
    projectId: 'sunify-4286b',
    databaseURL: 'https://sunify-4286b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunify-4286b.firebasestorage.app',
  );

}